### ISSUE TITLE
minSdk9 branch not functional on Gingerbread

### ISSUE THREAD

**Issue by mtotschnig** [eltos/SimpleDialogFragments#12]
While trying to use the SimpleColorDialog on Gingerbread I found the following problems:

1. mListView.setAdapter(mAdapter); in CustomListDialog
2. PorterDuff.Mode.ADD in ColorWheelView

were added in API 11 and lead to crash.

**Comment by mtotschnig** [comment]
First issue can be fixed with

```
        if (mListView instanceof ListView) {
            ((ListView) mListView).setAdapter(mAdapter);
        } else if (mListView instanceof GridView) {
            ((GridView) mListView).setAdapter(mAdapter);
        }
```

For second issue, I replaced ADD with SCREEN, but the result does not look good.
My suggestion would be not allow custom picker below Honeycomb.

**Comment by eltos** [comment]
I'm fine with that.
I'll update the Library shortly.
