### ISSUE TITLE
Hide the HEX EditView in SimpleColorWheelDialog

### ISSUE THREAD

**Issue by XanaRaquel** [eltos/SimpleDialogFragments#15]
When selecting to customize the color from the SimpleColorDialog, the SimpleColorWheelDialog show up and also the soft keyboard pops-up because the focus is in the EditView of the hex value and it's really annoying.

Either an way to disable it or don't give focus to it at the start would be great.

**Comment by eltos** [comment]
I did not manage to reproduce this. For me the Keyboard never shows up, when I open the ColorWheelDialog. I remember having worked on this quite a while ago, but I don't recall it exactly.
I was using the Demo APK on an Android 7.0 to verify this.

What Android version are you using?

As an idea, could you try whether adding the `<requestFocus/>` node to, lets say, the `SeekBar` [here](https://github.com/eltos/SimpleDialogFragments/blob/ce059a2839730b0589247c076d5428d2ccf05de8/simpledialogfragment/src/main/res/layout/simpledialogfragment_color_wheel.xml#L37) and [here](https://github.com/eltos/SimpleDialogFragments/blob/ce059a2839730b0589247c076d5428d2ccf05de8/simpledialogfragment/src/main/res/layout-land/simpledialogfragment_color_wheel.xml#L40) prevents the `EditText` from receiving focus on your device?

**Comment by XanaRaquel** [comment]
Using a device with Android 5.0.2 with a landscape only app.

I didn't know you could edit projects imported with gradle. Using your EDIT suggestion, it worked! But since I can edit the code I removed the hex EditText altogether. For this app it's not needed.

Thanks for the help!

**Comment by eltos** [comment]
I'm glad I could help
