### ISSUE TITLE
ColorWheelView.OnColorChangeListener is not public

### ISSUE THREAD

**Issue by Robyer** [eltos/SimpleDialogFragments#22]
I used ColorWheelView in my layout and I wanted to set `ColorPicker.setOnColorChangeListener(OnColorChangeListener listener);`, but I can't use/implement the `OnColorChangeListener` interface as it's marked package-private. It should be marked as public instead.

**Comment by eltos** [comment]
Fixed. Sorry for the inconvenience.

**Comment by eltos** [comment]
Published in [v2.2.2](https://github.com/eltos/SimpleDialogFragments/releases/tag/v2.2.2)
