### ISSUE TITLE
SimpleDialogFragments  show showHsvWheel problem with low res device

### ISSUE THREAD

**Issue by sf99** [eltos/SimpleDialogFragments#23]
## Steps to reproduce
1. Show dialog showHsvWheel  on low res device Landscape mode 720*580
2. 
3. 

## Expected and actual behaviour
Expected full dialog window  - get not full color picker window, some parts missed,  transparent and hex  are not fully visible and usable.  The window should be wider.
    
## Test Environment
Property | Value
 ------ | -------
Screen resolution | 580x720
Screen density |
Library version | 
Android version | 4.2

**Comment by eltos** [comment]
In order to reproduce this, not only the screen resolution is required, but - and more importantly - the screen density (dpi value or category).
And can you please provide a screenshot showing what you mean?

**Comment by sf99** [comment]
Hi,
thanks you for your quick response.

I am looking for nice and useful color picker for android devices ( small
or large ) and yours looks well.

I am trying to implement it with my app.
It looks OK in portrait mode, but in landscape mode it looks different with
different devices and different resolutions - not only small densities as I
have found.

I am sending you screenshots from emulators:

Nexus 4 , api 17  - portrait mode - OK,
the same Nexus 4 api 17 landscape mode - problem

Pixel C api 26 landscape mode  - problem

I am testing it also with some real devices and also with your
SimpleDialogFragments app. and it looks very different and not complete in
landscape mode for different devices/resolutions.

Best Regards

Slavomir

P.S.
It would be perfect to use new google libraries lv. 26 if it is possible.

**Comment by eltos** [comment]
Sorry to bother you with the same question again, but what screen densities do these devices have???

I have been testing it with the following configuration – and it works perfectly, both in portrait and landscape mode:

Property | Value
--- | ---
Screen Resolution | 2560×1440
**Screen denity** | **576 dpi**
Test app version | 2.2.1
Android version | 7.0 (API 24)

Also, where did you send these screenshots?

**Comment by sf99** [comment]
Nexus 4  768x1280 (~318  density)

Pixel C   2560x1800 (~318  density)

"Also, where did you send these screenshots? "
I am not sure, I understand well, I have sent them only to your mail.

Next screenshot is from my real device - tablet Lenovo A5500-F Android
4.4.2 800 x 1280 pixels, 16:10 ratio (~189 ppi density)  and
SimpleDialogfragments app. Landscape

Slavomir

**Comment by eltos** [comment]
I see, you commented via an email reply.
I don't think attachments are supported because I never received any. You can upload them to your comments by editing when using the webinterface.

**Comment by sf99** [comment]
OK I understand,
![screen_landscape1](https://user-images.githubusercontent.com/7030387/35519572-eec44ea0-0514-11e8-864f-dce73b451e7b.jpg)
![screen_landscape2](https://user-images.githubusercontent.com/7030387/35519573-eee55e42-0514-11e8-9370-60f3755b8c4a.jpg)
![screenshot_2018-01-29-12-07-48](https://user-images.githubusercontent.com/7030387/35519574-ef093312-0514-11e8-9b46-1ddccb5a5ba5.png)

**Comment by sf99** [comment]
It looks like simpledialogfragment_color_wheel layout land is OK, I have  test it separate as simple activity layout. The problem is using it with dialog.

**Comment by eltos** [comment]
So I ended up reworking the layout using ConstraintLayout, see the [constraintLayout-Branche](https://github.com/eltos/SimpleDialogFragments/tree/constraintLayout).
I tested it on the Nexus 4 (1280x768px, 318dpi, API23) and Pixel C (2560x1800px, 307dpi, API26) in both portrait and landscape mode without any issues.
Can you please confirm that the issue is solved in #24 so I can merge it?

**Comment by eltos** [comment]
Published in [v2.2.2](https://github.com/eltos/SimpleDialogFragments/releases/tag/v2.2.2)
