### ISSUE TITLE
Color choice dialog - how to specify a number of colors in one line?

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#28]
Your default color choice dialog has 5 colors in one line. How can I change this value to 4? for example?

**Comment by isabsent** [comment]
Have found:

    SimpleColorDialog.build().gridNumColumn(4);

**Comment by eltos** [comment]
Yes, sometimes it's helpful to take a look at the [Wiki](https://github.com/eltos/SimpleDialogFragments/wiki/CustomListDialog#available-customizations) :)
I guess that's why I even mentioned it in the issue-template ;)
