### ISSUE TITLE
Bounds for circles in the color edit dialog needed.

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#29]
When I try to show white color in the color chooser dialog it is invisible because  [it has the same color as a background](https://user-images.githubusercontent.com/4918293/36931222-15624326-1ee4-11e8-863e-f21e2a8f534a.png). It would be nice to have an opportunity to turn on black circle around the colors in the dialog builder.

**Comment by eltos** [comment]
Added [a new method here](https://github.com/eltos/SimpleDialogFragments/blob/289ae83d29e6cfa2a41e8ba34e3442c15127ba0e/simpledialogfragment/src/main/java/eltos/simpledialogfragment/color/SimpleColorDialog.java#L134-L143), so you can either do `.showOutline(SimpleColorDialog.AUTO)` or `.showOutline(Color.BLACK)`.

**Comment by isabsent** [comment]
Thanks a lot!
