### ISSUE TITLE
Custom Input Validation

### ISSUE THREAD

**Issue by codeAbode** [eltos/SimpleDialogFragments#3]
I am trying to user this great library but I have one issue. When using the SimpleFormDialog I cannot add my own validation for a username. Matchers work for many things but I need to be able to check for bad words customers may put into their username. Any suggestions?

**Comment by eltos** [comment]
If you don't want to create a pattern to filter these words, you can always use the [`SimpleFormDialog.InputValidator`](https://github.com/eltos/SimpleDialogFragments/blob/a3c2fa85cef8219ce2962351f98fa542e87f6c66/simpledialogfragment/src/main/java/eltos/simpledialogfragment/form/SimpleFormDialog.java#L159-L176) with your own implementation.

Just let the fragment or activity were you show your dialog implement the Interface and the dialog will automatically detect it and use the callback for validation (in addition to any other validations).

**Comment by eltos** [comment]
Just added a section about [Input Validation](https://github.com/eltos/SimpleDialogFragments/wiki/SimpleFormDialog#input-validation) to the wiki

**Comment by codeAbode** [comment]
Wow man what a quick response! and you actually made changes, I'm impressed. Thank you very much!

**Comment by eltos** [comment]
You're welcome :)


________________________________
Von: codeAbode <notifications@github.com>
Gesendet: 05.03.2017 20:38
An: eltos/SimpleDialogFragments
Cc: Philipp Niedermayer; Comment
Betreff: Re: [eltos/SimpleDialogFragments] Custom Input Validation (#3)


Wow man what a quick response! and you actually made changes, I'm impressed. Thank you very much!
