### ISSUE TITLE
File/Folder picker dialog

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#30]
I am going to create a [simple file/folder chooser](https://user-images.githubusercontent.com/4918293/37017274-9dc88e9a-2142-11e8-90b7-3f6d0e97d6eb.png) based on your library.  For this purpose I would like to extending your `SimpleListDialog`  and customize `onItemClick` :

    import android.view.View;
    import android.widget.AdapterView;
    
    import eltos.simpledialogfragment.list.SimpleListDialog;
    
    public class SimpleListDialogMod extends SimpleListDialog {
    
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            super.onItemClick(parent, view, position, id); 
            //Some custom code
        }
    }
and use it as follows:

    SimpleListDialogMod.build()
            .title(titleResId)
            .choiceMode(SimpleListDialog.SINGLE_CHOICE)
            .choiceMin(1)
            .items(itemNames)
            .extra(extras)
            .pos(R.string.button_deeper)
            .neg(R.string.button_up)
            .neut(R.string.button_pick)
            .show(this, PICK_DIALOG);
but `onItemClick` is never called when I press an item in the list! Why?

**P.S.** Would you be so kind to write your own SimplePickFileDialog? It is widely used and would be very useful as I suppose.

**Comment by eltos** [comment]
Given your code example, you are actually building a `SimpleListDialog` instead of a `SimpleListDialogMod`. Please have a look in the wiki [here](https://github.com/eltos/SimpleDialogFragments/wiki/CustomViewDialog#create-builder) and my answer on the related issue #19.

In my opinion Androids Storage Access Framework provides a really good and advanced document picker, so I personally don't think it's worth the effort creating a SimplePickFileDialog. But feel free to create a pull request once you completed your work ;)

**Comment by isabsent** [comment]
> Given your code example, you are actually building a `SimpleListDialog` instead of a `SimpleListDialogMod`. 

You  are right, thanks!

> Android Storage Access Framework provides a really good and advanced document picker...

I can lost some details, but it seems Android Storage Access Framework does not have an opportunity to pickup a **folder**.

**Comment by isabsent** [comment]
Please, give a hint - what is the simplest way to insert file or folder icon before each list item? Is it possible by extending a `SimpleListDialog` or it is necessary to extend `CustomListDialog`?

**Comment by eltos** [comment]
> I can lost some details, but it seems Android Storage Access Framework does not have an opportunity to pickup a folder.

It does: `Intent.ACTION_OPEN_DOCUMENT_TREE` (API 21+ only though)

> Please, give a hint - what is the simplest way to insert file or folder icon before each list item? Is it possible by extending a `SimpleListDialog` or it is necessary to extend `CustomListDialog`?

As said, I suggest to extend from `CustomListDialog` and write your own `AdvancedAdapter` implementation. The [wiki](https://github.com/eltos/SimpleDialogFragments/wiki/CustomListDialog) and [`SimpleListDialog`](https://github.com/eltos/SimpleDialogFragments/blob/master/simpledialogfragment/src/main/java/eltos/simpledialogfragment/list/SimpleListDialog.java) will give you some hints on how to do that.

**Comment by isabsent** [comment]
>It does: Intent.ACTION_OPEN_DOCUMENT_TREE (API 21+ only though)

Do you mean a DocumentFile.fromTreeUri(this, data.getData()) as a result of Android file picker? If yes, it is inacceptable when you need an access to the file with `RandomAccessFile`. It is impossible to get with Document File API unfortunately.

**Comment by isabsent** [comment]
[Enclosed zip-archive](https://github.com/eltos/SimpleDialogFragments/files/1796607/FilePicker.zip) is a simplest realization of a File/Folder Chooser for internal phone memory (in SINGLE_CHOICE mode only) based on your library.

**Comment by isabsent** [comment]
My implementation of [FIle/Folder Picker Dialog](https://github.com/isabsent/FilePicker) based on your library.

**Comment by eltos** [comment]
Great work @isabsent, looks good :)
I'll add a link to your extension in the readme. Or do you want to create a pull request?

**Comment by isabsent** [comment]
I have never made a pull request before and I am not sure my code is acceptable for you. I think it would be better if you take and change my code in consistence with your approach to the library construction.

**Comment by eltos** [comment]
I'm quite busy momentarily, so I won't be able to do this anytime soon.
