### ISSUE TITLE
Pin input dialog

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#32]
I need to show PIN code input dialog with number keyboard only. If I set `inputType(InputType.TYPE_CLASS_NUMBER)` as follows: 
            
             SimpleFormDialog.build()
                .extra(extras)
                .title("Title")
                .msg("Message")
                .fields(
                        Input.password(USER_PIN)
                                .showPasswordToggle(false)
                                .inputType(InputType.TYPE_CLASS_NUMBER)
                            )
                .neut()
                .cancelable(false)
                .show(this, CASH_BACK_DIALOG);
my PIN code becomes visible during input. If I remove `inputType(InputType.TYPE_CLASS_NUMBER)` PIN code is closed by stars during input, but keyboard has letter symbols too instead of numbers only. Is it posible to have closed PIN code input and numeric only keyboard?

**Comment by eltos** [comment]
That's possible, just specify the input type as follows:

    .inputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_TEXT_VARIATION_PASSWORD)

I think it's a good idea to add a method `Input.pin(...)` for this so I'll leave this issue open.

**Comment by isabsent** [comment]
Thanks!

**Comment by isabsent** [comment]
Sorry, but `.inputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_TEXT_VARIATION_PASSWORD)` doesn't work for me. Keyboard is numeric, but PIN-code is visible during input...

**Comment by eltos** [comment]
Sorry, it has to be TYPE_NUMBER_VARIATION_PASSWORD of course.

**Comment by eltos** [comment]
There will be a nice `SimplePinDialog` in the next release:


![screenshot_20180328-204208](https://user-images.githubusercontent.com/19860638/38049515-bba6f662-32c8-11e8-8e5d-da41f63c0900.jpg)
