### ISSUE TITLE
Is it possible to use dialogs as views? [Question][FeatureRequest]

### ISSUE THREAD

**Issue by shaljam** [eltos/SimpleDialogFragments#4]

**Comment by eltos** [comment]
Can you clarify what you mean by that?
Please provide an examplary use case.

**Comment by shaljam** [comment]
Sure, I'd like to use `SimpleColorDialog` as a fragment inside my activity to be present all the time, not like a dialog that opens and closes.

**Comment by eltos** [comment]
Please have a look at the commit referenced above. This should give you an Idea on how to re-use a view from a dialog in another fragment.

**Comment by eltos** [comment]
![screenshot_20170409-183849](https://cloud.githubusercontent.com/assets/19860638/24839035/e9675f6e-1d53-11e7-92aa-d206b3b45032.png)

**Comment by shaljam** [comment]
Great.
