### ISSUE TITLE
[Problem] Lib compiled under API 28 needed.

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#42]
It seems the new gradle plugin of AS 3.1 has problems compiling a project with your library in dependencies under API 28. Is it possible to make a new version of your lib under API 28 with "implementation" insead of "compile" and etc.?

**Comment by eltos** [comment]
An update to the latest API and support versions will be done with v3 of the library soon

**Comment by eltos** [comment]
I just published v3.0
