### ISSUE TITLE
Ability to show selected items if Dialog is called second time 

### ISSUE THREAD

**Issue by saintjab** [eltos/SimpleDialogFragments#43]
Thanks for this great library, very helpful and saved me time. I was thinking I would be great if there is a way to show selected items in the multi-choice mode especially if the same Dialog is shown for the second time, like if the user already picked some items from the list and then wanted to be sure of the selection or wants to add more items to the selection. Maybe something like

`SimpleListDialog.build()
                        .title("Select Categories")
                        .choiceMode(SimpleListDialog.MULTI_CHOICE)
                        .theme(R.style.MyFancyDialogTheme)
                        .choiceMax(5)
                        .items(getActivity(), R.array.activites)
                        .filterable(true)**.preselected(2, 6, 8)**
                        .show(registrationActivity, CATEGORY_DIALOG);`

**Comment by eltos** [comment]
Hey @saintjab,
thanks for your feedback.
The method you are looking for is actually called `choicePreset` (for indices) or `choiceIdPreset` (for ids).  
Have a look at the wiki [here](https://github.com/eltos/SimpleDialogFragments/wiki/CustomListDialog).

**Comment by saintjab** [comment]
Sorry, it looks like I didn't read the wikis thoroughly. Thanks for the pointer

**Comment by eltos** [comment]
No problem :)
