### ISSUE TITLE
Make automatic opening of Spinner when focusing optional

### ISSUE THREAD

**Issue by mtotschnig** [eltos/SimpleDialogFragments#45]
If the first form field in a SimpleFormDialog is a spinner, it automatically opens when the dialog is displayed. I think this is irritating at least in that circumstance. I am not sure if this has some benefit in other circumstances.

**Comment by eltos** [comment]
That's a future, not a bug.

The intention is to save the user from unnecessary clicks. It's for the same reason, that input fields are automatically focused and the keyboard is shown and one can use IME actions to go to the next field of the form etc.

**Comment by eltos** [comment]
If you have a different opinion on this, I think we can add an option to disable this behaviour. Have a look at [SimpleFormDialog.java#L237](https://github.com/eltos/SimpleDialogFragments/blob/master/simpledialogfragment/src/main/java/eltos/simpledialogfragment/form/SimpleFormDialog.java#L237).

**Comment by mtotschnig** [comment]
I understand the rationale, and I think it makes sense when navigating to the next field. That it is at least problematic on the first field, is demonstrated also after orientation change. Then the spinner is opened again even if user already has selected a value. But in general, when the dialog opens, I prefer to give the user a complete view of the form, which is hidden by the open spinner. As a consequence, I'd appreciate the option you suggest.
