### ISSUE TITLE
Set texts of buttons in ColorWheelDialog called from the custom color button in ColorDialog

### ISSUE THREAD

**Issue by AurumTheEnd** [eltos/SimpleDialogFragments#47]
So I'm using this library's ColorDialog for the user to pick a color from a predefined palette of mine in the res directory. I'm also allowing the user to pick his own color by pressing the palette icon in the color selection, which brings up the ColorWheelDialog.

This is the constructor I'm using: (the pre-selected color comes from the background color of the button which brings up the ColorDialog, and whose background color is updated in the callback)
```
SimpleColorDialog.build()
.title(getString(R.string.highlight_dialog_color_title))
.colors(getActivity(), R.array.highlightColors)
.allowCustom(true)
.colorPreset(ViewCompat.getBackgroundTintList(colorButton).getDefaultColor())
.pos(R.string.highlight_dialog_confirm)
.neg(R.string.highlight_dialog_cancel)
.show(KeyWordDialog.this, COLOR_DIALOG);
```

My question is: How can I also set the negative and positive buttons of the ColorWheelDialog, in which the user pics his custom color?

**Comment by eltos** [comment]
That's actually not possible currently, but shouldn't be much of an effort to implement...

**Comment by eltos** [comment]
One question: When you say you want to set the text of both buttons, do you intend to use any logic other than "ok/cancel" there?

**Comment by AurumTheEnd** [comment]
Okay, thank you for your time :)
