### ISSUE TITLE
Issue with input field layout

### ISSUE THREAD

**Issue by broakenmedia** [eltos/SimpleDialogFragments#54]
![image](https://user-images.githubusercontent.com/1523918/56901812-e61ce900-6a90-11e9-8e2f-2b57e4440e39.png)

**Comment by broakenmedia** [comment]
Is it possible to provide a custom style to the input?

**Comment by broakenmedia** [comment]
Presumably this is primarily down to:
https://github.com/material-components/material-components-android/issues/120

However the lack of customisation on the edittext means i am unable to workaround for the time being. Particularly lack of ability to set edittext width/height/style/padding/font size etc.

**Comment by eltos** [comment]
Have you tried changing the style via a custom theme (see customizations > theme in the [Wiki](https://github.com/eltos/SimpleDialogFragments/wiki/SimpleDialog#available-customizations))?

**Comment by eltos** [comment]
Can you check whether the issue occures for both, androidx and appcompat based library versions and whether both, SimpleInputDialog and/or SimpleFormDialog are effected?

**Comment by eltos** [comment]
> You can customize the style via a custom theme (see customizations > theme in the [Wiki](https://github.com/eltos/SimpleDialogFragments/wiki/SimpleDialog#available-customizations))

Did this work for you?

**Comment by mtotschnig** [comment]
I run in the same issue after updating material components to 1.2.1 in my project. I think the underlying issue is https://github.com/material-components/material-components-android/issues/1674

**Comment by mtotschnig** [comment]
My workaround is to build dialogs with the following theme passed in:

```
    <style name="SimpleDialog" parent="ThemeOverlay.MaterialComponents.Dialog.Alert">
        <item name="textInputStyle">@style/SimpleDialogTextInputStyle</item>
    </style>

    <style name="SimpleDialogTextInputStyle" parent="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu">
        <item name="endIconMode">none</item>
    </style>
```
