### ISSUE TITLE
[Question:] How to reference your Version 3.1 with AndroidX in build.gradle?

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#55]
How to reference your Version 3.1 with AndroidX in build.gradle?

**Comment by eltos** [comment]
As stated in the readme:

> You can use [JitPack](https://jitpack.io/#eltos/SimpleDialogFragments).

**Comment by isabsent** [comment]
Thanks. 

    implementation 'com.github.eltos:simpledialogfragment:3.1'
    implementation 'com.alimuzaffar.lib:pinentryedittext:2.0.6'
works too.

**Comment by NaturallyAsh** [comment]
omg thank you @isabsent for this!  I've been having absolutely no luck for days as to why my conversion to androidx kept failing jetify.  The pinentry lib needed to be updated to 2.0.6 b/c of a fix its previous version needed.  Refer people to this issue @eltos if you start getting issue complaints b/c of androidx.
