### ISSUE TITLE
Attribute application@allowBackup

### ISSUE THREAD

**Issue by Duna** [eltos/SimpleDialogFragments#56]
I am wondering why did you set in the library Attribute application@allowBackup = true?
This flag shall not be present in a library.

**Comment by eltos** [comment]
I didn't intentionally, that's probably a default.

**Comment by eltos** [comment]
It's a default setting generated by android studio (see https://medium.com/@elye.project/2-lines-in-manifest-to-remove-when-sharing-your-android-library-565d4c4af04a). I removed the attributes.
