### ISSUE TITLE
Add a method to get title, message and etc. of an already shown dialog.

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#61]
I am using your library to show errors from various threads. Two threads throw the same error like a "Server timeout" sometimes and I wouldn't show error dialog twice. To avoid this I need to check an existence of dialog with the message "Server timeout" and do nothing if it exists. But a method to get a message of the already shown dialog is absent and I have to do following in `androidx.fragment.app.Fragment`:

    public abstract class BaseFragment extends Fragment{
        private static final String CONVERSATION_ERROR_DIALOG = "dialogTagError";
        ...
        private boolean isErrorDialogAlreadyShown(String message){
            Fragment dialogFragment = getFragmentManager().findFragmentByTag(CONVERSATION_ERROR_DIALOG);
            return dialogFragment instanceof SimpleDialog && message.equals(dialogFragment.getArguments().getString(SimpleDialog.TAG + "message", null));
        }
    }

It would be nice to have the method 
 
    getFragmentManager().findFragmentByTag(DIALOG_TAG).getArguments().getString(SimpleDialog.TAG + "message", null)

ready in your library.

**Comment by eltos** [comment]
I see that the method is missing and might be useful.
In your use-case however I think it's more reasonable to use tags to identify if the dialog was already shown (as you do). So just make sure you have a unique tag for the "server-timeout" dialog and everything is fine. No need for this hacky checking of the title for dialog identification.

**Comment by eltos** [comment]
I added a new feature in e97533db354990939e71d6868c6eba6c589da320 that might be interesting for you:

You can now pass a `replaceTag` to the show dialog method. When set, this will cause an already shown dialog with this tag to be removed before showing the new dialog. By using the same tag twice you can make sure the dialog is only shown once.
```java
SimpleDialog.build()
            .title(R.string.error)
            .msg(R.string.network_error)
            .pos(R.string.retry)
            .show(this, CONVERSATION_ERROR_DIALOG, CONVERSATION_ERROR_DIALOG)
```
