### ISSUE TITLE
Duplicate Manifest.xml, Can't run or build apk

### ISSUE THREAD

**Issue by Fauzdar1** [eltos/SimpleDialogFragments#62]
This is a bug which occurs with Kotlin. It cannot build APK which also prevents running the app through ADB. I've also searched over google to find any solution but none worked. I also followed one solution to remove the manifest file from lint.jar and rebuild it but it didn't work either. I have also tried cleaning the project, invalidating caches, deleting gradle cache files etc, none worked.

Build error - `duplicate entry: AndroidManifest.xml`

Removing the library from the project resolves the error, adding it again gives the error. I remember including it my other project about 5 months ago and even back then it gave me the same error. I hope it will be solved as soon as possible. 

## Test Environment
| Property| Version |
|---|---|
|JavaVersion | `VERSION_1_8`|
|minSdkVersion | 23|
|compileSdkVersion| 29|
|targetSdkVersion |29|
|buildToolsVersion | 29.0.3|
|kotlin_version | 1.3.72|
|Lib version| 3.1 as in `implementation 'com.github.eltos:simpledialogfragment:3.1'`|

**Comment by eltos** [comment]
Are you using androidx? Try

    implementation 'com.github.eltos:simpledialogfragments:v3.1-androidx'

from jitpack (add `maven { url 'https://jitpack.io' }` to your repositories in your project level gradle file)

**Comment by Fauzdar1** [comment]
Yes, it worked. Also, I had to implement result listener to make the `onResult()` work. Thank you very much.
