### ISSUE TITLE
Migrate to JFrog

### ISSUE THREAD

**Issue by Duna** [eltos/SimpleDialogFragments#67]
The jcenter is closed down, would you like to migrate to mavencentral?
I cannot build your project dependency anymore

**Comment by eltos** [comment]
My Information is that JCenter/Bintray became read-only on May 1st, but will continue to serve artifacts until 2022. I am surprised you encounter such issues already now.
For the time being, you can also use jitpack.

**Comment by eltos** [comment]
So I published the library to Sonatype Maven Central Repository https://repo1.maven.org/maven2/io/github/eltos/simpledialogfragments/

Please note that I had to change the groupID: 
```groovy
dependencies {
    implementation 'io.github.eltos:simpledialogfragments:3.3.2'
}
```

**Comment by Duna** [comment]
Good.
