### ISSUE TITLE
Negative buttons & custom texts

### ISSUE THREAD

**Issue by oriolikart** [eltos/SimpleDialogFragments#7]
Hi ,

In the future it would be a nice functionalities: 
- Negative buttons
- Set custom text for positive & neagtive buttons

Regards!

**Comment by eltos** [comment]
These functions are of course already implemented. Please read the [docs](https://github.com/eltos/SimpleDialogFragments/wiki/SimpleDialog)!

(Correct me if I got you wrong)

**Comment by oriolikart** [comment]
OMG
I'm sorry dude, didn't see it.
Thank you and nice job!
