### ISSUE TITLE
SimpleFormDialog - vertical distanse between views.

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#83]
This code for the library version 3.5:

        SimpleFormDialog.build()
                .msg(R.string.dialog_message_new_server)
                .neg()
                .fields(
                        Check.box(SERVER_SSL).label(R.string.ssl).required().check(true),
                        Input.name(SERVER_ADDRESS).label(R.string.server_address).required().hint(R.string.pref_default_server_address).inputType(InputType.TYPE_CLASS_TEXT),
                        Input.name(SERVER_PORT).label(R.string.port).required().hint(R.string.pref_default_server_port).inputType(InputType.TYPE_CLASS_NUMBER)
                )
                .show(this, NEW_SERVER_DIALOG);

gives this [view](https://user-images.githubusercontent.com/4918293/193293625-316bccd0-216e-4404-a2ca-cda5702ce5d3.jpg) instead of [your nice picture](https://raw.githubusercontent.com/wiki/eltos/SimpleDialogFragments/screenshots/simpleformdialog.png)
What is a reason!?

**Comment by eltos** [comment]
Please read the wiki page on dialog styles: https://github.com/eltos/SimpleDialogFragments/wiki/Styles

**Comment by isabsent** [comment]
Thanks!
