### ISSUE TITLE
Support for Material3

### ISSUE THREAD

**Issue by mtotschnig** [eltos/SimpleDialogFragments#85]
Currently, it does not seem possible to achieve dialogues styled according to Material3 (https://m3.material.io/components/dialogs/overview) with this library, because MaterialComponents library requires dialogues to be created with MaterialAlertDialogBuilder instead of AlertDialog.Builder. 
Compare the current rendering:
![Screenshot_1684162871](https://github.com/eltos/SimpleDialogFragments/assets/1485456/575053c5-3ebf-4a91-a28c-b23e49335910)
with the one you can achieve by switching from AlertDialog.Builder to MaterialAlertDialogBuilder in SimpleDialog.java (and using a Material3 based theme.
![Screenshot_1684163001](https://github.com/eltos/SimpleDialogFragments/assets/1485456/1b491f1c-1262-4985-bb4d-c711cd7999f1)
I am not sure if this change still allows to use the older AppCompat or Material2 themes. In my test, I could not see any problem, but it would probably be safer, if based on the theme the one or the other DialogBuilder were used.

**Comment by eltos** [comment]
Thanks 👍

Since the [docs](https://developer.android.com/reference/com/google/android/material/dialog/MaterialAlertDialogBuilder) say
> An extension of AlertDialog.Builder for use with a Material theme [...]
> The type of dialog returned is still an AlertDialog; there is no specific Material implementation of AlertDialog.

it seams save to go for `MaterialAlertDialogBuilder` as a default. Needs to be tested thoroughly of course, but looks preferable.

Do you want to make a PR?

**Comment by eltos** [comment]
Did you just use `@style/SimpleDialogTheme.Material3` or a custom theme? Are there any changes to `@style/SimpleDialogTheme.Material3` required as well?

**Comment by mtotschnig** [comment]
Since, I do not have time to test this change thoroughly with non-M3 styles, I prefer to not take responsibility for it via a PR.
I am not aware of any changes needed for @style/SimpleDialogTheme.Material3. Just the activity where the dialogs are shown must inherit from a M3 style.

**Comment by mtotschnig** [comment]
Giving it another thought, I think it is safe to migrate to MaterialAlertDialogBuilder, although, it would change the appearance of the dialogues also in the case of Material2 themes (for example MaterialAlertDialogBuilder adds insets to the dialog window that might not be suitable for all apps, but these values can be set via style attributes). The reason I think so, is that this library requires at least a MaterialComponents theme anyway. It no longer works with AppCompat based themes since it uses components from the Material components library.

**Comment by eltos** [comment]
> The reason I think so, is that this library requires at least a MaterialComponents theme anyway. It no longer works with AppCompat based themes since it uses components from the Material components library.

It does use material components and its theme by default. But that doesn't mean AppCompat based themes are no longer supported. To keep AppCompat based themes working with `MaterialAlertDialogBuilder` I had to explicitly specify `colorSurface` there. Also, I clarified the style/theme names (keeping the old names as aliases), even though for M3 the default theme is sufficient.

See https://github.com/eltos/SimpleDialogFragments/wiki/Styles

**Comment by eltos** [comment]
Thank you @mtotschnig, excellent 👍

I think the M3 guidelines suggest the use of these full screen dialogs whenever a text input is involved, and especially for a form with so many fields it does make sense. Nevertheless I completely agree that the style is quite wasteful with space in general.
