### ISSUE TITLE
Material3 Full-Screen Dialogs

### ISSUE THREAD

**Issue by eltos** [eltos/SimpleDialogFragments#87]
From the [Material3 Design Guide](https://m3.material.io/components/dialogs/overview):

> Dialogs can require an action, communicate information, or help users accomplish a task. There are two types of dialogs: basic and full-screen.

![](https://lh3.googleusercontent.com/8ChV9ZXTL1eb2tWMArrvN1I5tofFH9xzT2thUkm4ifLGSq4w1E3OVKdQ9PXsKrrStMA6VMOEVXMBTJfDbr7CtRm2xo1QteldPabtO0Go8JQ=s0)

**Proposed method signatures**
```java
SimpleDialog.build()
            .title(R.string.hello)
            .msg(R.string.hello_world)
            .fullscreen() // or with true/false argument to en-/disable
            .show(Activity.this);
```

**Links**
- https://m3.material.io/components/dialogs/overview
- https://medium.com/alexander-schaefer/implementing-the-new-material-design-full-screen-dialog-for-android-e9dcc712cb38

**Comment by mtotschnig** [comment]
Shouldn't the argument default to false? 
For me, I am not sure if this adds value to this library, Given the requirement of a screen that should always appear fullscreen, I would probably not use a dialog fragment, but a standard fragment, or an activity.

**Comment by eltos** [comment]
I meant that `.fullscreen()` is equivalent to `.fullscreen(true)`, of course the default without that call is a standard pop up dialogue.

@mtotschnig So you don't think the simple API of this library and the features like it's form dialog would make use of it preferable over designing and implementing a new fragment or activity from scratch?

**Comment by mtotschnig** [comment]
> So you don't think the simple API of this library and it's features like the form dialog would make using it preferable over designing and implementing a new fragment or activity from scratch?

It probably depends on the use case. I think the simple API has its advantages for simple dialogs that I would want to render as a dialogue not full-screen. The advantage of using an activity is that the data can be passed in a type-safe way with Androidx Activity Result Contracts.
