### ISSUE TITLE
v3.8 JitPack build failed

### ISSUE THREAD

**Issue by Kntntn** [eltos/SimpleDialogFragments#91]
**Describe the bug**
https://jitpack.io/com/github/eltos/SimpleDialogFragments/v3.8/build.log

BUILD FAILED in 1s
Running: ./gradlew -Pgroup=com.github.eltos -Pversion=v3.8 publishToMavenLocal

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0/userguide/command_line_interface.html#sec:command_line_warnings
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/lintchecks/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':lintchecks'.
> Failed to apply plugin 'com.android.internal.lint'.
   > Could not create an instance of type com.android.build.gradle.internal.dsl.LintImpl$AgpDecorated.
      > Could not generate a decorated class for type LintImpl$AgpDecorated.
         > com/android/tools/lint/model/LintModelSeverity has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by eltos** [comment]
> com/android/tools/lint/model/LintModelSeverity has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Then JitPack needs to update their Java Runtime

**Comment by mtotschnig** [comment]
I think you need to tell Jitpack which Java version to use: https://jitpack.io/docs/BUILDING/#java-version

**Comment by mtotschnig** [comment]
Version 3.8 does not seem correctly published on MavenCentral. There is no aar:
https://repo1.maven.org/maven2/io/github/eltos/simpledialogfragments/3.8/
compared to
https://repo1.maven.org/maven2/io/github/eltos/simpledialogfragments/3.7/

**Comment by eltos** [comment]
Both should be fixed now
